baseURL = "https://digitalstart.lt"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Digital Start"
[[menu.main]]
URL = "about"
name = "Paslaptys"
weight = 1
[[menu.main]]
URL = "contact"
name = "Susisiekti"
weight = 4
[params]
address = "Vilnius"
author = "Dovydas Van Gucht"
copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = "Mes esame Digital Start - kÅ«rybiniÅ³ verslo sprendimÅ³ agentÅ«ra orientuota Ä¯ pardavimus. Mes padedame jums su svetainiÅ³ kurimu, socialiniÅ³ tinklÅ³ strategijomis, video bei kitais verslo sprendimais! Sveiki atvykÄ™ Ä¯ Digital Start."
email = "digitalstartagentura@gmail.com"
google_analytics_id = ""
home = "ğŸ "
logo = ""
phone = "+370 656 45000"
social = []
theme_color = "#13A6D1"
[params.contact]
enable = true
form_action = "https://formspree.io/xdowvqkg"
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = true
preloader = "images/preloader.gif"
